export const EstadoProyecto = {
  EN_PREPARACION: "EN_PREPARACION",
  LICITADO: "LICITADO",
  ADJUDICADO: "ADJUDICADO",
  EN_EJECUCION: "EN_EJECUCION",
  CON_OBSERVACIONES: "CON_OBSERVACIONES",
  SUSPENDIDO: "SUSPENDIDO",
  MODIFICADO: "MODIFICADO",
  FINALIZADO: "FINALIZADO",
  RECEPCIONADO: "RECEPCIONADO",
  TERMINADO_ANTICIPADAMENTE: "TERMINADO_ANTICIPADAMENTE",
  COBRO_DE_GARANTIA: "COBRO_DE_GARANTIA",
  CERRADO: "CERRADO"
} as const;

export const EstadoHito = {
  PENDIENTE: "PENDIENTE",
  ENTREGADO: "ENTREGADO",
  EN_REVISION_SERVIU: "EN_REVISION_SERVIU",
  CON_OBSERVACIONES: "CON_OBSERVACIONES",
  CORREGIDO: "CORREGIDO",
  APROBADO: "APROBADO",
  ATRASADO_CONSULTORA: "ATRASADO_CONSULTORA",
  ATRASADO_SERVIU: "ATRASADO_SERVIU"
} as const;

export const EstadoGarantia = {
  VIGENTE: "VIGENTE",
  PROXIMA_A_VENCER: "PROXIMA_A_VENCER",
  VENCIDA: "VENCIDA",
  PRORROGADA: "PRORROGADA",
  COBRO_SOLICITADO: "COBRO_SOLICITADO",
  COBRADA: "COBRADA"
} as const;

export const TipoModificacion = {
  AUMENTO_MONTO: "AUMENTO_MONTO",
  DISMINUCION_MONTO: "DISMINUCION_MONTO",
  AMPLIACION_PLAZO: "AMPLIACION_PLAZO",
  SUSPENSION: "SUSPENSION",
  REANUDACION: "REANUDACION",
  TERMINO_ANTICIPADO: "TERMINO_ANTICIPADO",
  MODIFICACION_MIXTA: "MODIFICACION_MIXTA"
} as const;

export const EstadoContrato = {
  VIGENTE: "VIGENTE",
  PROXIMO_A_VENCER: "PROXIMO_A_VENCER",
  VENCIDO: "VENCIDO",
  SUSPENDIDO: "SUSPENDIDO",
  TERMINADO: "TERMINADO"
} as const;

export const TipoAlerta = {
  HITO_ATRASADO_CONSULTORA: "HITO_ATRASADO_CONSULTORA",
  REVISION_SERVIU_ATRASADA: "REVISION_SERVIU_ATRASADA",
  GARANTIA_PROXIMA_A_VENCER: "GARANTIA_PROXIMA_A_VENCER",
  GARANTIA_VENCIDA: "GARANTIA_VENCIDA",
  CONTRATO_PROXIMO_A_VENCER: "CONTRATO_PROXIMO_A_VENCER",
  CONTRATO_VENCIDO: "CONTRATO_VENCIDO",
  HITOS_NO_SUMAN_100: "HITOS_NO_SUMAN_100"
} as const;

export const SeveridadAlerta = {
  BAJA: "BAJA",
  MEDIA: "MEDIA",
  ALTA: "ALTA",
  CRITICA: "CRITICA"
} as const;

export type EstadoProyecto = keyof typeof EstadoProyecto;
export type EstadoHito = keyof typeof EstadoHito;
export type EstadoGarantia = keyof typeof EstadoGarantia;
export type TipoModificacion = keyof typeof TipoModificacion;
export type EstadoContrato = keyof typeof EstadoContrato;
export type TipoAlerta = keyof typeof TipoAlerta;
export type SeveridadAlerta = keyof typeof SeveridadAlerta;
